In [1]:
# from vta_model.model_vta import ModelVta

# model = ModelVta(center_coord=[11.9492,-11.2413,-2.10106], output_path='/Users/cu135/hires_backdrops/test')
# model.run(radius_mm=2, filename='vta.nii')

In [2]:
import numpy as np

In [3]:
np.eye(4,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

Directional VTA Testing

In [4]:
coords= [
		[10.2682,-14.0467,-7.73696]]
len(coords)

1

In [5]:
coords= [
		[10.2682,-14.0467,-7.73696],
		[11.3144,-12.8041,-6.17608],
		[10.2054,-12.8406,-5.87032],
		[10.9189,-13.6905,-5.57142],
		[11.8759,-11.8691,-4.30005],
		[10.7628,-11.8979,-4.00238],
		[11.4891,-12.7585,-3.69509],
		[11.9492,-11.2413,-2.10106]
	]

In [6]:
print(np.array(coords))

[[ 10.2682  -14.0467   -7.73696]
 [ 11.3144  -12.8041   -6.17608]
 [ 10.2054  -12.8406   -5.87032]
 [ 10.9189  -13.6905   -5.57142]
 [ 11.8759  -11.8691   -4.30005]
 [ 10.7628  -11.8979   -4.00238]
 [ 11.4891  -12.7585   -3.69509]
 [ 11.9492  -11.2413   -2.10106]]


Test VTA Generation

In [7]:
from vta_model.model_directional_vta import ModelDirectionalVta
vtamodel = ModelDirectionalVta(contact_coordinates=coords[1:4],
                                origin_index=0,
                                voxel_size = [0.2, 0.2, 0.2],
                                grid_shape = [71, 71, 71],
                                output_path = "/Users/cu135/hires_backdrops/test",
                                fname = "directional_vta.nii")
vtamodel.run(radius_mm=2)

[ 11.3144  -12.8041   -6.17608]  R: [ 10.2054  -12.8406   -5.87032]
[ 11.3144  -12.8041   -6.17608]  R: [ 10.9189  -13.6905   -5.57142]


Test VTA Optimizer

In [8]:
nifti_path = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/optimizer/BIDMCBERMDST_nosubj9_Gait_UPDRS_Rand_exch_vox_vstat_pcc_inverse_r_map.nii'
base_path = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/optimizer/datasets/CbctDbs0282'

In [ ]:
from processing_utils.run_optimizer import nii_to_mni, process_data
mni_coords = nii_to_mni(nifti_path)
process_data(base_path, mni_coords)

ModuleNotFoundError: No module named 'processing'

from processing